### PR TITLE
Alternative way to install JS kernel for Jupyter

### PR DESCRIPTION
**Pull request by edouard-gv**

### CODE REVIEW

**Comment by parmentelat** [comment]
I am really not familiar with Windows ;)
however I did test this on a Windows VBox and it worked for me
maybe I should also say that our students have git-bash installed (as part of git for windows, 2 birds 1 stone)
and so this is what I used during my tests as well, of course

anyways, all I'm saying is, the present phrasing suggests this alternative is the only way on Windows, maybe we could be a little more informative as to which setups are likely to require that alternative ?

and btw iiuc that you've actually done that install, thanks for taking the time :-)

**Comment by edouard-gv** [comment]
Please find a new wording. Do not hesitate to amend it.

And yet I was able to install it from scratch. Quite long indeed. And not being able to launch python on my Git shell I used standard cmd.

**Comment by parmentelat** [comment]
thanks !

**Comment by parmentelat** [comment]
> And yet I was able to install it from scratch. Quite long indeed. And not being able to launch python on my Git shell I used standard cmd.

this being semester 2, all the students are expected to have a working common stack with
miniconda + bash + git + vscode
clearly I was making this strong assumption here, I'll try to make this more explicit

FYI the installation instructions for that common stack can be found here:
https://github.com/ue12-p21/python-primer/blob/next-year/notebooks/2-01-intro.md
https://github.com/ue12-p21/python-primer/blob/next-year/notebooks/2-02-outils.md

**Comment by edouard-gv** [comment]
Yes! The answer was in it: "dans GitBash vous *devez* tapez à la place python
-i(le -i est pour *interactive*) pour avoir un interpréteur interactif"

Thank you ;).

Le mar. 25 janv. 2022 à 08:51, parmentelat ***@***.***> a
écrit :

**Pull request merged**
